HTTPError: include code and reason in exception.
Include error code and reason in the HTTPError exception message so that
code and reason are printed when in the traceback.